name: twinkle
description: Twinkle is a Java library for creating text-based user interfaces.
authors:
- Tako Schotanus (tako@codejive.org)
links:
  homepage: https://github.com/codejive/java-twinkle
  repository: https://github.com/codejive/java-twinkle
  documentation: https://github.com/codejive/java-twinkle/blob/main/README.md
java: 8
dependencies:
actions:
  clean: ./mvnw clean
  build: ./mvnw spotless:apply package -DskipTests
  test: ./mvnw test
